gh-pr: Handle empty repositories (#30)
Instead of throwing an error an giving up
error: org/repo: git clone error: remote repository is empty
report it and move on
org/repo empty repository